# Generated by Django 3.0.5 on 2020-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='логин покупателя')),
                ('item', models.CharField(max_length=200, verbose_name='наименование товара')),
                ('total', models.IntegerField(verbose_name='сумма сделки')),
                ('quantity', models.IntegerField(verbose_name='количество товара')),
                ('date', models.DateTimeField(verbose_name='дата и время регистрации сделки')),
            ],
        ),
    ]
